"""progress and content columns

Revision ID: 987e64920685
Revises: 26824da404dc
Create Date: 2026-09-26 00:08:54.799538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '987e64920685'
down_revision: Union[str, Sequence[str], None] = '26824da404dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # games / game_versions are empty before this revision (content came from seed files),
    # so the NOT NULL slug needs no backfill.
    op.create_index('ix_attempts_user_version_seed', 'attempts', ['user_id', 'game_version_id', 'seed'], unique=False)
    op.add_column('game_versions', sa.Column('title', sa.String(length=120), nullable=False, server_default=''))
    op.add_column('game_versions', sa.Column('objective', sa.Text(), nullable=False, server_default=''))
    op.add_column('game_versions', sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('games', sa.Column('slug', sa.String(length=80), nullable=False))
    op.create_unique_constraint(op.f('uq_games_slug'), 'games', ['slug'])
    op.add_column('topic_progress', sa.Column('lesson_done_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarded_at')
    op.drop_column('topic_progress', 'lesson_done_at')
    op.drop_constraint(op.f('uq_games_slug'), 'games', type_='unique')
    op.drop_column('games', 'slug')
    op.drop_column('game_versions', 'rules')
    op.drop_column('game_versions', 'objective')
    op.drop_column('game_versions', 'title')
    op.drop_index('ix_attempts_user_version_seed', table_name='attempts')
    # ### end Alembic commands ###
