"""initial schema

Revision ID: 26824da404dc
Revises: 
Create Date: 2026-09-25 15:24:24.305851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26824da404dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='content_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks')),
    sa.UniqueConstraint('slug', name=op.f('uq_tracks_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('user', 'content_editor', 'super_admin', name='user_role'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('email_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('verify', 'reset', name='email_token_purpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_tokens_token_hash'))
    )
    op.create_index(op.f('ix_email_tokens_user_id'), 'email_tokens', ['user_id'], unique=False)
    op.create_table('levels',
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('district_key', sa.String(length=40), nullable=False),
    sa.Column('story_intro', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='content_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_levels_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_levels')),
    sa.UniqueConstraint('track_id', 'slug', name=op.f('uq_levels_track_id'))
    )
    op.create_index(op.f('ix_levels_track_id'), 'levels', ['track_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('chapters',
    sa.Column('level_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='content_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_chapters_level_id_levels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters')),
    sa.UniqueConstraint('level_id', 'slug', name=op.f('uq_chapters_level_id'))
    )
    op.create_index(op.f('ix_chapters_level_id'), 'chapters', ['level_id'], unique=False)
    op.create_table('topics',
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='content_status'), nullable=False),
    sa.Column('pass_threshold', sa.Integer(), nullable=False),
    sa.Column('required_games_count', sa.Integer(), nullable=False),
    sa.Column('hints_allowed', sa.Boolean(), nullable=False),
    sa.Column('retest_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_topics_chapter_id_chapters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('chapter_id', 'slug', name=op.f('uq_topics_chapter_id'))
    )
    op.create_index(op.f('ix_topics_chapter_id'), 'topics', ['chapter_id'], unique=False)
    op.create_table('games',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('game_type', sa.String(length=40), nullable=False),
    sa.Column('is_checkpoint', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='content_status'), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_games_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_topic_id'), 'games', ['topic_id'], unique=False)
    op.create_table('topic_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'unlocked', 'passed', name='topic_progress_status'), nullable=False),
    sa.Column('best_score', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.Column('passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_topic_progress_topic_id_topics'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_topic_progress_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'topic_id', name=op.f('pk_topic_progress'))
    )
    op.create_table('game_versions',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scenario', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=False),
    sa.Column('editable_region', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('public_tests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hidden_test_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variant_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_solution', sa.Text(), nullable=False),
    sa.Column('visualizer_type', sa.String(length=40), nullable=False),
    sa.Column('character_key', sa.String(length=40), nullable=False),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dialogue', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_game_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_versions_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_versions')),
    sa.UniqueConstraint('game_id', 'version', name=op.f('uq_game_versions_game_id'))
    )
    op.create_index(op.f('ix_game_versions_game_id'), 'game_versions', ['game_id'], unique=False)
    # games <-> game_versions is a cycle; add this FK once both tables exist
    op.create_foreign_key(
        op.f('fk_games_current_version_id_game_versions'),
        'games', 'game_versions', ['current_version_id'], ['id'], ondelete='SET NULL',
    )
    op.create_table('attempts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('game_version_id', sa.Uuid(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_checkpoint', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_version_id'], ['game_versions.id'], name=op.f('fk_attempts_game_version_id_game_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    op.create_index(op.f('ix_attempts_game_version_id'), 'attempts', ['game_version_id'], unique=False)
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_game_version_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_constraint(
        op.f('fk_games_current_version_id_game_versions'), 'games', type_='foreignkey'
    )
    op.drop_index(op.f('ix_game_versions_game_id'), table_name='game_versions')
    op.drop_table('game_versions')
    op.drop_table('topic_progress')
    op.drop_index(op.f('ix_games_topic_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_topics_chapter_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_chapters_level_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_levels_track_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_email_tokens_user_id'), table_name='email_tokens')
    op.drop_table('email_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tracks')
    for enum_name in ('content_status', 'user_role', 'email_token_purpose', 'topic_progress_status'):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
