"""track interests and learning goal

Revision ID: b0de7ed0e716
Revises: 987e64920685
Create Date: 2026-09-26 01:25:52.346168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0de7ed0e716'
down_revision: Union[str, Sequence[str], None] = '987e64920685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track_interests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_interests_track_id_tracks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_track_interests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'track_id', name=op.f('pk_track_interests'))
    )
    op.create_index(op.f('ix_track_interests_track_id'), 'track_interests', ['track_id'], unique=False)
    op.add_column('users', sa.Column('learning_goal', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'learning_goal')
    op.drop_index(op.f('ix_track_interests_track_id'), table_name='track_interests')
    op.drop_table('track_interests')
    # ### end Alembic commands ###
